name: Build

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}
          #token: ${{ secrets.TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g twilio-cli
      - run: twilio plugins:install @twilio-labs/plugin-flex
      - run: npm install
      - run: npm test

      - name: Create bundle
        run: npm run build
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}

      - name: Commit bundled assets
        run: |
          git cp build/* assets/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets
          git diff --staged --quiet || (git commit -m "Updating assets" && git push)