name: Bundle and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm install -g twilio-cli
      - run: twilio plugins:install @twilio-labs/plugin-flex

      - name: Create bundle
        run: npm run build

      - name: Find package version
        id: packageVersion
        run: echo "package_json=$(cat package.json | tr -d "\n")" >> $GITHUB_OUTPUT

      - name: Create Release
        run: gh release create -d "v${{ fromJson(steps.packageVersion.outputs.package_json).version }}" ./build/*.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
