name: PR validator

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - 'assets/**'
  push:
    branches:
      - main
    paths:
      - 'assets/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps: echo "Unit Test execution not required. Passing status check"
